Document: aseqrc
Title: Debian aseqrc Manual
Author: <insert document author here>
Abstract: This manual describes what aseqrc is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/aseqrc/aseqrc.sgml.gz

Format: postscript
Files: /usr/share/doc/aseqrc/aseqrc.ps.gz

Format: text
Files: /usr/share/doc/aseqrc/aseqrc.text.gz

Format: HTML
Index: /usr/share/doc/aseqrc/html/index.html
Files: /usr/share/doc/aseqrc/html/*.html
